// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/zhongbang.proto

package proto_zhongbang

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpenAcctRequest struct {
	TrueName             string   `protobuf:"bytes,1,opt,name=trueName,proto3" json:"trueName,omitempty"`
	Certno               string   `protobuf:"bytes,2,opt,name=certno,proto3" json:"certno,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Cardno               string   `protobuf:"bytes,4,opt,name=cardno,proto3" json:"cardno,omitempty"`
	Bankno               string   `protobuf:"bytes,5,opt,name=bankno,proto3" json:"bankno,omitempty"`
	BankName             string   `protobuf:"bytes,6,opt,name=bankName,proto3" json:"bankName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenAcctRequest) Reset()         { *m = OpenAcctRequest{} }
func (m *OpenAcctRequest) String() string { return proto.CompactTextString(m) }
func (*OpenAcctRequest) ProtoMessage()    {}
func (*OpenAcctRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{0}
}

func (m *OpenAcctRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenAcctRequest.Unmarshal(m, b)
}
func (m *OpenAcctRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenAcctRequest.Marshal(b, m, deterministic)
}
func (m *OpenAcctRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenAcctRequest.Merge(m, src)
}
func (m *OpenAcctRequest) XXX_Size() int {
	return xxx_messageInfo_OpenAcctRequest.Size(m)
}
func (m *OpenAcctRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenAcctRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenAcctRequest proto.InternalMessageInfo

func (m *OpenAcctRequest) GetTrueName() string {
	if m != nil {
		return m.TrueName
	}
	return ""
}

func (m *OpenAcctRequest) GetCertno() string {
	if m != nil {
		return m.Certno
	}
	return ""
}

func (m *OpenAcctRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *OpenAcctRequest) GetCardno() string {
	if m != nil {
		return m.Cardno
	}
	return ""
}

func (m *OpenAcctRequest) GetBankno() string {
	if m != nil {
		return m.Bankno
	}
	return ""
}

func (m *OpenAcctRequest) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

type OpenQueryRequest struct {
	Certno               string   `protobuf:"bytes,1,opt,name=certno,proto3" json:"certno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenQueryRequest) Reset()         { *m = OpenQueryRequest{} }
func (m *OpenQueryRequest) String() string { return proto.CompactTextString(m) }
func (*OpenQueryRequest) ProtoMessage()    {}
func (*OpenQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{1}
}

func (m *OpenQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenQueryRequest.Unmarshal(m, b)
}
func (m *OpenQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenQueryRequest.Marshal(b, m, deterministic)
}
func (m *OpenQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenQueryRequest.Merge(m, src)
}
func (m *OpenQueryRequest) XXX_Size() int {
	return xxx_messageInfo_OpenQueryRequest.Size(m)
}
func (m *OpenQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenQueryRequest proto.InternalMessageInfo

func (m *OpenQueryRequest) GetCertno() string {
	if m != nil {
		return m.Certno
	}
	return ""
}

type OpenAcctResponse struct {
	RespCode             string   `protobuf:"bytes,1,opt,name=respCode,proto3" json:"respCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StatusDesc           string   `protobuf:"bytes,4,opt,name=statusDesc,proto3" json:"statusDesc,omitempty"`
	TrueName             string   `protobuf:"bytes,5,opt,name=trueName,proto3" json:"trueName,omitempty"`
	Certno               string   `protobuf:"bytes,6,opt,name=certno,proto3" json:"certno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenAcctResponse) Reset()         { *m = OpenAcctResponse{} }
func (m *OpenAcctResponse) String() string { return proto.CompactTextString(m) }
func (*OpenAcctResponse) ProtoMessage()    {}
func (*OpenAcctResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{2}
}

func (m *OpenAcctResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenAcctResponse.Unmarshal(m, b)
}
func (m *OpenAcctResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenAcctResponse.Marshal(b, m, deterministic)
}
func (m *OpenAcctResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenAcctResponse.Merge(m, src)
}
func (m *OpenAcctResponse) XXX_Size() int {
	return xxx_messageInfo_OpenAcctResponse.Size(m)
}
func (m *OpenAcctResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenAcctResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenAcctResponse proto.InternalMessageInfo

func (m *OpenAcctResponse) GetRespCode() string {
	if m != nil {
		return m.RespCode
	}
	return ""
}

func (m *OpenAcctResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OpenAcctResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OpenAcctResponse) GetStatusDesc() string {
	if m != nil {
		return m.StatusDesc
	}
	return ""
}

func (m *OpenAcctResponse) GetTrueName() string {
	if m != nil {
		return m.TrueName
	}
	return ""
}

func (m *OpenAcctResponse) GetCertno() string {
	if m != nil {
		return m.Certno
	}
	return ""
}

type VirtPayRequest struct {
	PayType              string   `protobuf:"bytes,1,opt,name=payType,proto3" json:"payType,omitempty"`
	PayMode              string   `protobuf:"bytes,2,opt,name=payMode,proto3" json:"payMode,omitempty"`
	SubType              string   `protobuf:"bytes,3,opt,name=subType,proto3" json:"subType,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,4,opt,name=notifyUrl,proto3" json:"notifyUrl,omitempty"`
	Traceno              string   `protobuf:"bytes,5,opt,name=traceno,proto3" json:"traceno,omitempty"`
	Amount               string   `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Accountno            string   `protobuf:"bytes,7,opt,name=accountno,proto3" json:"accountno,omitempty"`
	AccountName          string   `protobuf:"bytes,8,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Mobile               string   `protobuf:"bytes,9,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Certno               string   `protobuf:"bytes,10,opt,name=certno,proto3" json:"certno,omitempty"`
	Bankno               string   `protobuf:"bytes,11,opt,name=bankno,proto3" json:"bankno,omitempty"`
	BankName             string   `protobuf:"bytes,12,opt,name=bankName,proto3" json:"bankName,omitempty"`
	BankType             string   `protobuf:"bytes,13,opt,name=bankType,proto3" json:"bankType,omitempty"`
	Remark               string   `protobuf:"bytes,14,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtPayRequest) Reset()         { *m = VirtPayRequest{} }
func (m *VirtPayRequest) String() string { return proto.CompactTextString(m) }
func (*VirtPayRequest) ProtoMessage()    {}
func (*VirtPayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{3}
}

func (m *VirtPayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtPayRequest.Unmarshal(m, b)
}
func (m *VirtPayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtPayRequest.Marshal(b, m, deterministic)
}
func (m *VirtPayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtPayRequest.Merge(m, src)
}
func (m *VirtPayRequest) XXX_Size() int {
	return xxx_messageInfo_VirtPayRequest.Size(m)
}
func (m *VirtPayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtPayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtPayRequest proto.InternalMessageInfo

func (m *VirtPayRequest) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *VirtPayRequest) GetPayMode() string {
	if m != nil {
		return m.PayMode
	}
	return ""
}

func (m *VirtPayRequest) GetSubType() string {
	if m != nil {
		return m.SubType
	}
	return ""
}

func (m *VirtPayRequest) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *VirtPayRequest) GetTraceno() string {
	if m != nil {
		return m.Traceno
	}
	return ""
}

func (m *VirtPayRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *VirtPayRequest) GetAccountno() string {
	if m != nil {
		return m.Accountno
	}
	return ""
}

func (m *VirtPayRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *VirtPayRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *VirtPayRequest) GetCertno() string {
	if m != nil {
		return m.Certno
	}
	return ""
}

func (m *VirtPayRequest) GetBankno() string {
	if m != nil {
		return m.Bankno
	}
	return ""
}

func (m *VirtPayRequest) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *VirtPayRequest) GetBankType() string {
	if m != nil {
		return m.BankType
	}
	return ""
}

func (m *VirtPayRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type VirtPayResponse struct {
	RespCode             string   `protobuf:"bytes,1,opt,name=respCode,proto3" json:"respCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Traceno              string   `protobuf:"bytes,3,opt,name=traceno,proto3" json:"traceno,omitempty"`
	Orderno              string   `protobuf:"bytes,4,opt,name=orderno,proto3" json:"orderno,omitempty"`
	Amount               string   `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	TransStatus          string   `protobuf:"bytes,6,opt,name=transStatus,proto3" json:"transStatus,omitempty"`
	PayStatus            string   `protobuf:"bytes,7,opt,name=payStatus,proto3" json:"payStatus,omitempty"`
	PayMsg               string   `protobuf:"bytes,8,opt,name=payMsg,proto3" json:"payMsg,omitempty"`
	Signature            string   `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtPayResponse) Reset()         { *m = VirtPayResponse{} }
func (m *VirtPayResponse) String() string { return proto.CompactTextString(m) }
func (*VirtPayResponse) ProtoMessage()    {}
func (*VirtPayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{4}
}

func (m *VirtPayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtPayResponse.Unmarshal(m, b)
}
func (m *VirtPayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtPayResponse.Marshal(b, m, deterministic)
}
func (m *VirtPayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtPayResponse.Merge(m, src)
}
func (m *VirtPayResponse) XXX_Size() int {
	return xxx_messageInfo_VirtPayResponse.Size(m)
}
func (m *VirtPayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtPayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VirtPayResponse proto.InternalMessageInfo

func (m *VirtPayResponse) GetRespCode() string {
	if m != nil {
		return m.RespCode
	}
	return ""
}

func (m *VirtPayResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VirtPayResponse) GetTraceno() string {
	if m != nil {
		return m.Traceno
	}
	return ""
}

func (m *VirtPayResponse) GetOrderno() string {
	if m != nil {
		return m.Orderno
	}
	return ""
}

func (m *VirtPayResponse) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *VirtPayResponse) GetTransStatus() string {
	if m != nil {
		return m.TransStatus
	}
	return ""
}

func (m *VirtPayResponse) GetPayStatus() string {
	if m != nil {
		return m.PayStatus
	}
	return ""
}

func (m *VirtPayResponse) GetPayMsg() string {
	if m != nil {
		return m.PayMsg
	}
	return ""
}

func (m *VirtPayResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*OpenAcctRequest)(nil), "proto.zhongbang.OpenAcctRequest")
	proto.RegisterType((*OpenQueryRequest)(nil), "proto.zhongbang.OpenQueryRequest")
	proto.RegisterType((*OpenAcctResponse)(nil), "proto.zhongbang.OpenAcctResponse")
	proto.RegisterType((*VirtPayRequest)(nil), "proto.zhongbang.VirtPayRequest")
	proto.RegisterType((*VirtPayResponse)(nil), "proto.zhongbang.VirtPayResponse")
}

func init() { proto.RegisterFile("proto/zhongbang.proto", fileDescriptor_810593aaaa2edd2b) }

var fileDescriptor_810593aaaa2edd2b = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0x5a, 0x9a, 0x6e, 0xa7, 0xb0, 0x45, 0x91, 0x58, 0x59, 0x08, 0xa1, 0xaa, 0x27, 0xc4,
	0x61, 0x39, 0xf0, 0x0b, 0x10, 0x5c, 0x97, 0x8f, 0xe5, 0xe3, 0xee, 0xa4, 0x43, 0x88, 0x76, 0x63,
	0x07, 0xdb, 0x39, 0x84, 0x1f, 0x80, 0xc4, 0x4f, 0xe1, 0xce, 0x0f, 0x44, 0xe3, 0xb1, 0x9d, 0x04,
	0xd4, 0xd3, 0x9e, 0xea, 0xf7, 0xc6, 0x1f, 0x6f, 0xde, 0xbc, 0x06, 0x1e, 0x75, 0x46, 0x3b, 0xfd,
	0xe2, 0xc7, 0x37, 0xad, 0xea, 0x52, 0xaa, 0xfa, 0xd2, 0xe3, 0x62, 0xe7, 0x7f, 0x2e, 0x13, 0x7d,
	0xf8, 0x9d, 0xc1, 0xee, 0x5d, 0x87, 0xea, 0x55, 0x55, 0xb9, 0x6b, 0xfc, 0xde, 0xa3, 0x75, 0xc5,
	0x63, 0x38, 0x73, 0xa6, 0xc7, 0xb7, 0xb2, 0x45, 0x91, 0xed, 0xb3, 0x67, 0x9b, 0xeb, 0x84, 0x8b,
	0x0b, 0xc8, 0x2b, 0x34, 0x4e, 0x69, 0xb1, 0xf0, 0x95, 0x80, 0x88, 0x6f, 0x75, 0xd9, 0xdc, 0xa2,
	0x58, 0x32, 0xcf, 0xc8, 0xef, 0x97, 0xe6, 0xa8, 0xb4, 0xb8, 0x17, 0xf6, 0x7b, 0x44, 0x7c, 0x29,
	0xd5, 0x8d, 0xd2, 0x62, 0xc5, 0x3c, 0x23, 0x7a, 0x9b, 0x56, 0xfe, 0xed, 0x9c, 0xdf, 0x8e, 0xf8,
	0xf0, 0x1c, 0x1e, 0x92, 0xd4, 0x0f, 0x3d, 0x9a, 0x21, 0x6a, 0x1d, 0xf5, 0x64, 0x53, 0x3d, 0x87,
	0x3f, 0x19, 0x6f, 0xe6, 0xbe, 0x6c, 0xa7, 0x95, 0x45, 0xba, 0xdc, 0xa0, 0xed, 0x5e, 0xeb, 0x63,
	0x6a, 0x2c, 0xe2, 0x42, 0xc0, 0xba, 0x45, 0x6b, 0x65, 0x8d, 0xa1, 0xb3, 0x08, 0xe9, 0x09, 0xeb,
	0xa4, 0xeb, 0x6d, 0x6c, 0x8d, 0x51, 0xf1, 0x14, 0x80, 0x57, 0x6f, 0xd0, 0x56, 0xa1, 0xbd, 0x09,
	0x33, 0xb3, 0x71, 0x75, 0xd2, 0xc6, 0x7c, 0x26, 0xfb, 0xe7, 0x12, 0xce, 0xbf, 0x34, 0xc6, 0xbd,
	0x97, 0xa9, 0x43, 0x01, 0xeb, 0x4e, 0x0e, 0x9f, 0x86, 0x2e, 0x6a, 0x8e, 0x30, 0x54, 0xae, 0xa8,
	0x9b, 0x45, 0xaa, 0x5c, 0x85, 0x66, 0x6c, 0x5f, 0xfa, 0x33, 0xac, 0x39, 0xc2, 0xe2, 0x09, 0x6c,
	0x94, 0x76, 0xcd, 0xd7, 0xe1, 0xb3, 0xb9, 0x0d, 0x9a, 0x47, 0x82, 0xce, 0x39, 0x23, 0x2b, 0x4c,
	0x63, 0x89, 0x90, 0x04, 0xcb, 0x56, 0xf7, 0xca, 0x45, 0xc1, 0x8c, 0xe8, 0x3e, 0x59, 0x55, 0xb4,
	0x54, 0x5a, 0xac, 0xf9, 0xbe, 0x44, 0x14, 0x7b, 0xd8, 0x06, 0xe0, 0x5d, 0x38, 0xf3, 0xf5, 0x29,
	0x35, 0xc9, 0xcd, 0xe6, 0xbf, 0xdc, 0xb0, 0x41, 0xf0, 0x6f, 0xce, 0x42, 0x6e, 0xb6, 0x27, 0x73,
	0x73, 0x7f, 0x9e, 0x9b, 0x58, 0xf3, 0x76, 0x3c, 0x18, 0x6b, 0xde, 0x8f, 0x0b, 0xc8, 0x0d, 0xb6,
	0xd2, 0xdc, 0x88, 0x73, 0xbe, 0x8f, 0xd1, 0xe1, 0xd7, 0x02, 0x76, 0x69, 0x10, 0x77, 0x8a, 0xcf,
	0xc4, 0xd3, 0xe5, 0xdc, 0x53, 0x01, 0x6b, 0x6d, 0x8e, 0x68, 0xd2, 0x9f, 0x23, 0xc2, 0x89, 0xdb,
	0xab, 0x99, 0xdb, 0x7b, 0xd8, 0x3a, 0x23, 0x95, 0xfd, 0xc8, 0x79, 0xe4, 0x51, 0x4c, 0x29, 0x9a,
	0x47, 0x27, 0x87, 0x50, 0x0f, 0xf3, 0x48, 0x04, 0xdd, 0x4b, 0x11, 0xb1, 0x75, 0x18, 0x45, 0x40,
	0x74, 0xca, 0x36, 0xb5, 0x92, 0xae, 0x37, 0x71, 0x10, 0x23, 0x51, 0xe6, 0xfe, 0xa3, 0xf1, 0xf2,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0xa4, 0x5f, 0x6d, 0x54, 0x04, 0x00, 0x00,
}
