// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/zhongbang.proto

package proto_zhongbang

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpenAcctRequest struct {
	TrueName             string   `protobuf:"bytes,1,opt,name=trueName,proto3" json:"trueName,omitempty"`
	Certno               string   `protobuf:"bytes,2,opt,name=certno,proto3" json:"certno,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Cardno               string   `protobuf:"bytes,4,opt,name=cardno,proto3" json:"cardno,omitempty"`
	Bankno               string   `protobuf:"bytes,5,opt,name=bankno,proto3" json:"bankno,omitempty"`
	BankName             string   `protobuf:"bytes,6,opt,name=bankName,proto3" json:"bankName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenAcctRequest) Reset()         { *m = OpenAcctRequest{} }
func (m *OpenAcctRequest) String() string { return proto.CompactTextString(m) }
func (*OpenAcctRequest) ProtoMessage()    {}
func (*OpenAcctRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{0}
}

func (m *OpenAcctRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenAcctRequest.Unmarshal(m, b)
}
func (m *OpenAcctRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenAcctRequest.Marshal(b, m, deterministic)
}
func (m *OpenAcctRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenAcctRequest.Merge(m, src)
}
func (m *OpenAcctRequest) XXX_Size() int {
	return xxx_messageInfo_OpenAcctRequest.Size(m)
}
func (m *OpenAcctRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenAcctRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenAcctRequest proto.InternalMessageInfo

func (m *OpenAcctRequest) GetTrueName() string {
	if m != nil {
		return m.TrueName
	}
	return ""
}

func (m *OpenAcctRequest) GetCertno() string {
	if m != nil {
		return m.Certno
	}
	return ""
}

func (m *OpenAcctRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *OpenAcctRequest) GetCardno() string {
	if m != nil {
		return m.Cardno
	}
	return ""
}

func (m *OpenAcctRequest) GetBankno() string {
	if m != nil {
		return m.Bankno
	}
	return ""
}

func (m *OpenAcctRequest) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

type OpenQueryRequest struct {
	Certno               string   `protobuf:"bytes,1,opt,name=certno,proto3" json:"certno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenQueryRequest) Reset()         { *m = OpenQueryRequest{} }
func (m *OpenQueryRequest) String() string { return proto.CompactTextString(m) }
func (*OpenQueryRequest) ProtoMessage()    {}
func (*OpenQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{1}
}

func (m *OpenQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenQueryRequest.Unmarshal(m, b)
}
func (m *OpenQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenQueryRequest.Marshal(b, m, deterministic)
}
func (m *OpenQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenQueryRequest.Merge(m, src)
}
func (m *OpenQueryRequest) XXX_Size() int {
	return xxx_messageInfo_OpenQueryRequest.Size(m)
}
func (m *OpenQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenQueryRequest proto.InternalMessageInfo

func (m *OpenQueryRequest) GetCertno() string {
	if m != nil {
		return m.Certno
	}
	return ""
}

type OpenAcctResponse struct {
	RespCode             string   `protobuf:"bytes,1,opt,name=respCode,proto3" json:"respCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StatusDesc           string   `protobuf:"bytes,4,opt,name=statusDesc,proto3" json:"statusDesc,omitempty"`
	TrueName             string   `protobuf:"bytes,5,opt,name=trueName,proto3" json:"trueName,omitempty"`
	Certno               string   `protobuf:"bytes,6,opt,name=certno,proto3" json:"certno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenAcctResponse) Reset()         { *m = OpenAcctResponse{} }
func (m *OpenAcctResponse) String() string { return proto.CompactTextString(m) }
func (*OpenAcctResponse) ProtoMessage()    {}
func (*OpenAcctResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{2}
}

func (m *OpenAcctResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenAcctResponse.Unmarshal(m, b)
}
func (m *OpenAcctResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenAcctResponse.Marshal(b, m, deterministic)
}
func (m *OpenAcctResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenAcctResponse.Merge(m, src)
}
func (m *OpenAcctResponse) XXX_Size() int {
	return xxx_messageInfo_OpenAcctResponse.Size(m)
}
func (m *OpenAcctResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenAcctResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenAcctResponse proto.InternalMessageInfo

func (m *OpenAcctResponse) GetRespCode() string {
	if m != nil {
		return m.RespCode
	}
	return ""
}

func (m *OpenAcctResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OpenAcctResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OpenAcctResponse) GetStatusDesc() string {
	if m != nil {
		return m.StatusDesc
	}
	return ""
}

func (m *OpenAcctResponse) GetTrueName() string {
	if m != nil {
		return m.TrueName
	}
	return ""
}

func (m *OpenAcctResponse) GetCertno() string {
	if m != nil {
		return m.Certno
	}
	return ""
}

type VirtPayRequest struct {
	PayType              string   `protobuf:"bytes,1,opt,name=payType,proto3" json:"payType,omitempty"`
	PayMode              string   `protobuf:"bytes,2,opt,name=payMode,proto3" json:"payMode,omitempty"`
	SubType              string   `protobuf:"bytes,3,opt,name=subType,proto3" json:"subType,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,4,opt,name=notifyUrl,proto3" json:"notifyUrl,omitempty"`
	Traceno              string   `protobuf:"bytes,5,opt,name=traceno,proto3" json:"traceno,omitempty"`
	Amount               string   `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Accountno            string   `protobuf:"bytes,7,opt,name=accountno,proto3" json:"accountno,omitempty"`
	AccountName          string   `protobuf:"bytes,8,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Mobile               string   `protobuf:"bytes,9,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Certno               string   `protobuf:"bytes,10,opt,name=certno,proto3" json:"certno,omitempty"`
	Bankno               string   `protobuf:"bytes,11,opt,name=bankno,proto3" json:"bankno,omitempty"`
	BankName             string   `protobuf:"bytes,12,opt,name=bankName,proto3" json:"bankName,omitempty"`
	BankType             string   `protobuf:"bytes,13,opt,name=bankType,proto3" json:"bankType,omitempty"`
	Remark               string   `protobuf:"bytes,14,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtPayRequest) Reset()         { *m = VirtPayRequest{} }
func (m *VirtPayRequest) String() string { return proto.CompactTextString(m) }
func (*VirtPayRequest) ProtoMessage()    {}
func (*VirtPayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{3}
}

func (m *VirtPayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtPayRequest.Unmarshal(m, b)
}
func (m *VirtPayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtPayRequest.Marshal(b, m, deterministic)
}
func (m *VirtPayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtPayRequest.Merge(m, src)
}
func (m *VirtPayRequest) XXX_Size() int {
	return xxx_messageInfo_VirtPayRequest.Size(m)
}
func (m *VirtPayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtPayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtPayRequest proto.InternalMessageInfo

func (m *VirtPayRequest) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *VirtPayRequest) GetPayMode() string {
	if m != nil {
		return m.PayMode
	}
	return ""
}

func (m *VirtPayRequest) GetSubType() string {
	if m != nil {
		return m.SubType
	}
	return ""
}

func (m *VirtPayRequest) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *VirtPayRequest) GetTraceno() string {
	if m != nil {
		return m.Traceno
	}
	return ""
}

func (m *VirtPayRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *VirtPayRequest) GetAccountno() string {
	if m != nil {
		return m.Accountno
	}
	return ""
}

func (m *VirtPayRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *VirtPayRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *VirtPayRequest) GetCertno() string {
	if m != nil {
		return m.Certno
	}
	return ""
}

func (m *VirtPayRequest) GetBankno() string {
	if m != nil {
		return m.Bankno
	}
	return ""
}

func (m *VirtPayRequest) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *VirtPayRequest) GetBankType() string {
	if m != nil {
		return m.BankType
	}
	return ""
}

func (m *VirtPayRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type VirtPayResponse struct {
	RespCode             string   `protobuf:"bytes,1,opt,name=respCode,proto3" json:"respCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Traceno              string   `protobuf:"bytes,3,opt,name=traceno,proto3" json:"traceno,omitempty"`
	Orderno              string   `protobuf:"bytes,4,opt,name=orderno,proto3" json:"orderno,omitempty"`
	Amount               string   `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	TransStatus          string   `protobuf:"bytes,6,opt,name=transStatus,proto3" json:"transStatus,omitempty"`
	PayStatus            string   `protobuf:"bytes,7,opt,name=payStatus,proto3" json:"payStatus,omitempty"`
	PayMsg               string   `protobuf:"bytes,8,opt,name=payMsg,proto3" json:"payMsg,omitempty"`
	Signature            string   `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtPayResponse) Reset()         { *m = VirtPayResponse{} }
func (m *VirtPayResponse) String() string { return proto.CompactTextString(m) }
func (*VirtPayResponse) ProtoMessage()    {}
func (*VirtPayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{4}
}

func (m *VirtPayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtPayResponse.Unmarshal(m, b)
}
func (m *VirtPayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtPayResponse.Marshal(b, m, deterministic)
}
func (m *VirtPayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtPayResponse.Merge(m, src)
}
func (m *VirtPayResponse) XXX_Size() int {
	return xxx_messageInfo_VirtPayResponse.Size(m)
}
func (m *VirtPayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtPayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VirtPayResponse proto.InternalMessageInfo

func (m *VirtPayResponse) GetRespCode() string {
	if m != nil {
		return m.RespCode
	}
	return ""
}

func (m *VirtPayResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VirtPayResponse) GetTraceno() string {
	if m != nil {
		return m.Traceno
	}
	return ""
}

func (m *VirtPayResponse) GetOrderno() string {
	if m != nil {
		return m.Orderno
	}
	return ""
}

func (m *VirtPayResponse) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *VirtPayResponse) GetTransStatus() string {
	if m != nil {
		return m.TransStatus
	}
	return ""
}

func (m *VirtPayResponse) GetPayStatus() string {
	if m != nil {
		return m.PayStatus
	}
	return ""
}

func (m *VirtPayResponse) GetPayMsg() string {
	if m != nil {
		return m.PayMsg
	}
	return ""
}

func (m *VirtPayResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type VirtOrderRequest struct {
	Traceno              string   `protobuf:"bytes,1,opt,name=traceno,proto3" json:"traceno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtOrderRequest) Reset()         { *m = VirtOrderRequest{} }
func (m *VirtOrderRequest) String() string { return proto.CompactTextString(m) }
func (*VirtOrderRequest) ProtoMessage()    {}
func (*VirtOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{5}
}

func (m *VirtOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtOrderRequest.Unmarshal(m, b)
}
func (m *VirtOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtOrderRequest.Marshal(b, m, deterministic)
}
func (m *VirtOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtOrderRequest.Merge(m, src)
}
func (m *VirtOrderRequest) XXX_Size() int {
	return xxx_messageInfo_VirtOrderRequest.Size(m)
}
func (m *VirtOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtOrderRequest proto.InternalMessageInfo

func (m *VirtOrderRequest) GetTraceno() string {
	if m != nil {
		return m.Traceno
	}
	return ""
}

type BalanceRequest struct {
	Cardno               string   `protobuf:"bytes,1,opt,name=cardno,proto3" json:"cardno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{6}
}

func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (m *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(m, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetCardno() string {
	if m != nil {
		return m.Cardno
	}
	return ""
}

type BalanceResponse struct {
	RespCode             string   `protobuf:"bytes,1,opt,name=respCode,proto3" json:"respCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance              string   `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Transit              string   `protobuf:"bytes,5,opt,name=transit,proto3" json:"transit,omitempty"`
	Frozen               string   `protobuf:"bytes,6,opt,name=frozen,proto3" json:"frozen,omitempty"`
	Signature            string   `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{7}
}

func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (m *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(m, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetRespCode() string {
	if m != nil {
		return m.RespCode
	}
	return ""
}

func (m *BalanceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BalanceResponse) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *BalanceResponse) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *BalanceResponse) GetTransit() string {
	if m != nil {
		return m.Transit
	}
	return ""
}

func (m *BalanceResponse) GetFrozen() string {
	if m != nil {
		return m.Frozen
	}
	return ""
}

func (m *BalanceResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type VirtNotifyRequest struct {
	Amount               string   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Cardno               string   `protobuf:"bytes,2,opt,name=cardno,proto3" json:"cardno,omitempty"`
	Fee                  string   `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
	Merchno              string   `protobuf:"bytes,4,opt,name=merchno,proto3" json:"merchno,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Orderno              string   `protobuf:"bytes,6,opt,name=orderno,proto3" json:"orderno,omitempty"`
	TransStatus          string   `protobuf:"bytes,7,opt,name=transStatus,proto3" json:"transStatus,omitempty"`
	PayStatus            string   `protobuf:"bytes,8,opt,name=payStatus,proto3" json:"payStatus,omitempty"`
	Traceno              string   `protobuf:"bytes,9,opt,name=traceno,proto3" json:"traceno,omitempty"`
	TransDate            string   `protobuf:"bytes,10,opt,name=transDate,proto3" json:"transDate,omitempty"`
	TransTime            string   `protobuf:"bytes,11,opt,name=transTime,proto3" json:"transTime,omitempty"`
	Signature            string   `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtNotifyRequest) Reset()         { *m = VirtNotifyRequest{} }
func (m *VirtNotifyRequest) String() string { return proto.CompactTextString(m) }
func (*VirtNotifyRequest) ProtoMessage()    {}
func (*VirtNotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810593aaaa2edd2b, []int{8}
}

func (m *VirtNotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtNotifyRequest.Unmarshal(m, b)
}
func (m *VirtNotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtNotifyRequest.Marshal(b, m, deterministic)
}
func (m *VirtNotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtNotifyRequest.Merge(m, src)
}
func (m *VirtNotifyRequest) XXX_Size() int {
	return xxx_messageInfo_VirtNotifyRequest.Size(m)
}
func (m *VirtNotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtNotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtNotifyRequest proto.InternalMessageInfo

func (m *VirtNotifyRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *VirtNotifyRequest) GetCardno() string {
	if m != nil {
		return m.Cardno
	}
	return ""
}

func (m *VirtNotifyRequest) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *VirtNotifyRequest) GetMerchno() string {
	if m != nil {
		return m.Merchno
	}
	return ""
}

func (m *VirtNotifyRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VirtNotifyRequest) GetOrderno() string {
	if m != nil {
		return m.Orderno
	}
	return ""
}

func (m *VirtNotifyRequest) GetTransStatus() string {
	if m != nil {
		return m.TransStatus
	}
	return ""
}

func (m *VirtNotifyRequest) GetPayStatus() string {
	if m != nil {
		return m.PayStatus
	}
	return ""
}

func (m *VirtNotifyRequest) GetTraceno() string {
	if m != nil {
		return m.Traceno
	}
	return ""
}

func (m *VirtNotifyRequest) GetTransDate() string {
	if m != nil {
		return m.TransDate
	}
	return ""
}

func (m *VirtNotifyRequest) GetTransTime() string {
	if m != nil {
		return m.TransTime
	}
	return ""
}

func (m *VirtNotifyRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*OpenAcctRequest)(nil), "proto.zhongbang.OpenAcctRequest")
	proto.RegisterType((*OpenQueryRequest)(nil), "proto.zhongbang.OpenQueryRequest")
	proto.RegisterType((*OpenAcctResponse)(nil), "proto.zhongbang.OpenAcctResponse")
	proto.RegisterType((*VirtPayRequest)(nil), "proto.zhongbang.VirtPayRequest")
	proto.RegisterType((*VirtPayResponse)(nil), "proto.zhongbang.VirtPayResponse")
	proto.RegisterType((*VirtOrderRequest)(nil), "proto.zhongbang.VirtOrderRequest")
	proto.RegisterType((*BalanceRequest)(nil), "proto.zhongbang.BalanceRequest")
	proto.RegisterType((*BalanceResponse)(nil), "proto.zhongbang.BalanceResponse")
	proto.RegisterType((*VirtNotifyRequest)(nil), "proto.zhongbang.VirtNotifyRequest")
}

func init() { proto.RegisterFile("proto/zhongbang.proto", fileDescriptor_810593aaaa2edd2b) }

var fileDescriptor_810593aaaa2edd2b = []byte{
	// 630 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0x93, 0x2f, 0x76, 0x73, 0xdb, 0x2f, 0x09, 0x96, 0xa8, 0x2c, 0x54, 0xa1, 0xc8, 0xab,
	0x0a, 0xa1, 0xb2, 0xe0, 0x09, 0x80, 0x6e, 0xdb, 0x42, 0x29, 0xec, 0xc7, 0xce, 0x24, 0xb5, 0x1a,
	0xcf, 0x98, 0x99, 0xf1, 0x22, 0x7d, 0x00, 0x24, 0x1e, 0x85, 0x3d, 0x2f, 0xc1, 0x13, 0xf0, 0x3a,
	0xe8, 0xce, 0x9f, 0x67, 0x52, 0x55, 0x2c, 0xba, 0x8a, 0xcf, 0xb9, 0xe3, 0x99, 0x73, 0xcf, 0x3d,
	0xe3, 0xc0, 0xf3, 0x4e, 0x70, 0xc5, 0xdf, 0xdc, 0xdf, 0x72, 0xb6, 0xa9, 0x08, 0xdb, 0x9c, 0x69,
	0x9c, 0xcf, 0xf5, 0xcf, 0x99, 0xa7, 0xcb, 0x9f, 0x09, 0xcc, 0xaf, 0x3a, 0xca, 0xde, 0xd5, 0xb5,
	0xba, 0xa6, 0xdf, 0x7a, 0x2a, 0x55, 0xfe, 0x02, 0x0e, 0x94, 0xe8, 0xe9, 0x25, 0x69, 0x69, 0x91,
	0x2c, 0x93, 0xd3, 0xe9, 0xb5, 0xc7, 0xf9, 0x31, 0xa4, 0x35, 0x15, 0x8a, 0xf1, 0x62, 0xa4, 0x2b,
	0x16, 0x21, 0xdf, 0xf2, 0xaa, 0xd9, 0xd2, 0x62, 0x6c, 0x78, 0x83, 0xf4, 0x7a, 0x22, 0x56, 0x8c,
	0x17, 0xff, 0xd9, 0xf5, 0x1a, 0x21, 0x5f, 0x11, 0x76, 0xc7, 0x78, 0x31, 0x31, 0xbc, 0x41, 0x78,
	0x36, 0x3e, 0xe9, 0xb3, 0x53, 0x73, 0xb6, 0xc3, 0xe5, 0x2b, 0x58, 0xa0, 0xd4, 0x4f, 0x3d, 0x15,
	0x3b, 0xa7, 0x75, 0xd0, 0x93, 0x84, 0x7a, 0xca, 0x5f, 0x89, 0x59, 0x6c, 0xfa, 0x92, 0x1d, 0x67,
	0x92, 0xe2, 0xe6, 0x82, 0xca, 0xee, 0x03, 0x5f, 0xf9, 0xc6, 0x1c, 0xce, 0x0b, 0xc8, 0x5a, 0x2a,
	0x25, 0xd9, 0x50, 0xdb, 0x99, 0x83, 0x78, 0x84, 0x54, 0x44, 0xf5, 0xd2, 0xb5, 0x66, 0x50, 0xfe,
	0x12, 0xc0, 0x3c, 0x9d, 0x53, 0x59, 0xdb, 0xf6, 0x02, 0x26, 0xb2, 0x71, 0xf2, 0xa8, 0x8d, 0x69,
	0x24, 0xfb, 0xfb, 0x18, 0x66, 0x5f, 0x1b, 0xa1, 0x3e, 0x12, 0xdf, 0x61, 0x01, 0x59, 0x47, 0x76,
	0x37, 0xbb, 0xce, 0x69, 0x76, 0xd0, 0x56, 0x2e, 0xb0, 0x9b, 0x91, 0xaf, 0x5c, 0xd8, 0x66, 0x64,
	0x5f, 0xe9, 0x77, 0x8c, 0x66, 0x07, 0xf3, 0x13, 0x98, 0x32, 0xae, 0x9a, 0xf5, 0xee, 0x8b, 0xd8,
	0x5a, 0xcd, 0x03, 0x81, 0xef, 0x29, 0x41, 0x6a, 0xea, 0xc7, 0xe2, 0x20, 0x0a, 0x26, 0x2d, 0xef,
	0x99, 0x72, 0x82, 0x0d, 0xc2, 0xfd, 0x48, 0x5d, 0xe3, 0x23, 0xe3, 0x45, 0x66, 0xf6, 0xf3, 0x44,
	0xbe, 0x84, 0x43, 0x0b, 0xb4, 0x0b, 0x07, 0xba, 0x1e, 0x52, 0x41, 0x6e, 0xa6, 0x0f, 0x72, 0x63,
	0x0c, 0x82, 0xfd, 0x9c, 0xd9, 0xdc, 0x1c, 0x3e, 0x9a, 0x9b, 0xa3, 0x38, 0x37, 0xae, 0xa6, 0xed,
	0xf8, 0x7f, 0xa8, 0x69, 0x3f, 0x8e, 0x21, 0x15, 0xb4, 0x25, 0xe2, 0xae, 0x98, 0x99, 0xfd, 0x0c,
	0x2a, 0x7f, 0x8c, 0x60, 0xee, 0x07, 0xf1, 0xa4, 0xf8, 0x04, 0x9e, 0x8e, 0x63, 0x4f, 0x0b, 0xc8,
	0xb8, 0x58, 0x51, 0xe1, 0x2f, 0x87, 0x83, 0x81, 0xdb, 0x93, 0xc8, 0xed, 0x25, 0x1c, 0x2a, 0x41,
	0x98, 0xfc, 0x6c, 0xf2, 0x68, 0x46, 0x11, 0x52, 0x38, 0x8f, 0x8e, 0xec, 0x6c, 0xdd, 0xce, 0xc3,
	0x13, 0xb8, 0x2f, 0x46, 0x44, 0x6e, 0xec, 0x28, 0x2c, 0xc2, 0xb7, 0x64, 0xb3, 0x61, 0x44, 0xf5,
	0xc2, 0x0d, 0x62, 0x20, 0xca, 0xd7, 0xb0, 0x40, 0x2b, 0xae, 0x50, 0x5c, 0x90, 0x4a, 0xd7, 0x55,
	0x12, 0x75, 0x55, 0x9e, 0xc2, 0xec, 0x3d, 0xd9, 0x12, 0x56, 0xd3, 0xf0, 0x8e, 0x9a, 0x6f, 0x40,
	0x12, 0x7e, 0x03, 0xca, 0xdf, 0x09, 0xcc, 0xfd, 0xd2, 0xa7, 0x5e, 0x51, 0xeb, 0xd7, 0x38, 0xf2,
	0xab, 0x80, 0xac, 0x32, 0x07, 0x38, 0x87, 0x2d, 0xb4, 0xfa, 0x99, 0x6c, 0x54, 0x90, 0x74, 0x84,
	0xb8, 0xd7, 0x5a, 0xf0, 0x7b, 0xca, 0x5c, 0xd2, 0x0d, 0x8a, 0x3d, 0xca, 0xf6, 0x3d, 0xfa, 0x33,
	0x82, 0x67, 0x68, 0xd2, 0xa5, 0xbe, 0x4b, 0x41, 0xe7, 0x56, 0x57, 0x12, 0xe9, 0x1a, 0x1c, 0x19,
	0x45, 0x5f, 0xc5, 0x05, 0x8c, 0xd7, 0xd4, 0xdd, 0x59, 0x7c, 0x34, 0x3d, 0x8b, 0xfa, 0x76, 0xc8,
	0x88, 0x85, 0xa1, 0x1b, 0x93, 0x07, 0x89, 0x73, 0xb9, 0x4a, 0xe3, 0x5c, 0xed, 0xe5, 0x27, 0xfb,
	0x47, 0x7e, 0x0e, 0xf6, 0xf3, 0x13, 0x4c, 0x7d, 0x1a, 0x67, 0xf9, 0x04, 0xa6, 0x7a, 0x9b, 0x73,
	0xa2, 0xa8, 0xbd, 0xb2, 0x03, 0xe1, 0xab, 0x37, 0x4d, 0x4b, 0xed, 0xc5, 0x1d, 0x88, 0xd8, 0xd9,
	0xa3, 0x3d, 0x67, 0xab, 0x54, 0xff, 0x65, 0xbd, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x6f,
	0xae, 0xb1, 0xd2, 0x06, 0x00, 0x00,
}
