// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: proto/zhongbang.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OpenAcctRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrueName string `protobuf:"bytes,1,opt,name=trueName,proto3" json:"trueName,omitempty"`
	Certno   string `protobuf:"bytes,2,opt,name=certno,proto3" json:"certno,omitempty"`
	Mobile   string `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Cardno   string `protobuf:"bytes,4,opt,name=cardno,proto3" json:"cardno,omitempty"`
	Bankno   string `protobuf:"bytes,5,opt,name=bankno,proto3" json:"bankno,omitempty"`
	BankName string `protobuf:"bytes,6,opt,name=bankName,proto3" json:"bankName,omitempty"`
}

func (x *OpenAcctRequest) Reset() {
	*x = OpenAcctRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_zhongbang_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenAcctRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAcctRequest) ProtoMessage() {}

func (x *OpenAcctRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zhongbang_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAcctRequest.ProtoReflect.Descriptor instead.
func (*OpenAcctRequest) Descriptor() ([]byte, []int) {
	return file_proto_zhongbang_proto_rawDescGZIP(), []int{0}
}

func (x *OpenAcctRequest) GetTrueName() string {
	if x != nil {
		return x.TrueName
	}
	return ""
}

func (x *OpenAcctRequest) GetCertno() string {
	if x != nil {
		return x.Certno
	}
	return ""
}

func (x *OpenAcctRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *OpenAcctRequest) GetCardno() string {
	if x != nil {
		return x.Cardno
	}
	return ""
}

func (x *OpenAcctRequest) GetBankno() string {
	if x != nil {
		return x.Bankno
	}
	return ""
}

func (x *OpenAcctRequest) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

type OpenQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Certno string `protobuf:"bytes,1,opt,name=certno,proto3" json:"certno,omitempty"`
}

func (x *OpenQueryRequest) Reset() {
	*x = OpenQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_zhongbang_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenQueryRequest) ProtoMessage() {}

func (x *OpenQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zhongbang_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenQueryRequest.ProtoReflect.Descriptor instead.
func (*OpenQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_zhongbang_proto_rawDescGZIP(), []int{1}
}

func (x *OpenQueryRequest) GetCertno() string {
	if x != nil {
		return x.Certno
	}
	return ""
}

type OpenAcctResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespCode    string `protobuf:"bytes,1,opt,name=respCode,proto3" json:"respCode,omitempty"`
	Message     string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status      string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StatusDesc  string `protobuf:"bytes,4,opt,name=statusDesc,proto3" json:"statusDesc,omitempty"`
	TrueName    string `protobuf:"bytes,5,opt,name=trueName,proto3" json:"trueName,omitempty"`
	Certno      string `protobuf:"bytes,6,opt,name=certno,proto3" json:"certno,omitempty"`
	Balance     string `protobuf:"bytes,7,opt,name=balance,proto3" json:"balance,omitempty"`
	BankAccount string `protobuf:"bytes,8,opt,name=bankAccount,proto3" json:"bankAccount,omitempty"`
}

func (x *OpenAcctResponse) Reset() {
	*x = OpenAcctResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_zhongbang_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenAcctResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAcctResponse) ProtoMessage() {}

func (x *OpenAcctResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zhongbang_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAcctResponse.ProtoReflect.Descriptor instead.
func (*OpenAcctResponse) Descriptor() ([]byte, []int) {
	return file_proto_zhongbang_proto_rawDescGZIP(), []int{2}
}

func (x *OpenAcctResponse) GetRespCode() string {
	if x != nil {
		return x.RespCode
	}
	return ""
}

func (x *OpenAcctResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OpenAcctResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OpenAcctResponse) GetStatusDesc() string {
	if x != nil {
		return x.StatusDesc
	}
	return ""
}

func (x *OpenAcctResponse) GetTrueName() string {
	if x != nil {
		return x.TrueName
	}
	return ""
}

func (x *OpenAcctResponse) GetCertno() string {
	if x != nil {
		return x.Certno
	}
	return ""
}

func (x *OpenAcctResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *OpenAcctResponse) GetBankAccount() string {
	if x != nil {
		return x.BankAccount
	}
	return ""
}

type VirtPayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayType     string `protobuf:"bytes,1,opt,name=payType,proto3" json:"payType,omitempty"`
	PayMode     string `protobuf:"bytes,2,opt,name=payMode,proto3" json:"payMode,omitempty"`
	SubType     string `protobuf:"bytes,3,opt,name=subType,proto3" json:"subType,omitempty"`
	NotifyUrl   string `protobuf:"bytes,4,opt,name=notifyUrl,proto3" json:"notifyUrl,omitempty"`
	Traceno     string `protobuf:"bytes,5,opt,name=traceno,proto3" json:"traceno,omitempty"`
	Amount      string `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Accountno   string `protobuf:"bytes,7,opt,name=accountno,proto3" json:"accountno,omitempty"`
	AccountName string `protobuf:"bytes,8,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Mobile      string `protobuf:"bytes,9,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Certno      string `protobuf:"bytes,10,opt,name=certno,proto3" json:"certno,omitempty"`
	Bankno      string `protobuf:"bytes,11,opt,name=bankno,proto3" json:"bankno,omitempty"`
	BankName    string `protobuf:"bytes,12,opt,name=bankName,proto3" json:"bankName,omitempty"`
	BankType    string `protobuf:"bytes,13,opt,name=bankType,proto3" json:"bankType,omitempty"`
	Remark      string `protobuf:"bytes,14,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *VirtPayRequest) Reset() {
	*x = VirtPayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_zhongbang_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtPayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtPayRequest) ProtoMessage() {}

func (x *VirtPayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zhongbang_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtPayRequest.ProtoReflect.Descriptor instead.
func (*VirtPayRequest) Descriptor() ([]byte, []int) {
	return file_proto_zhongbang_proto_rawDescGZIP(), []int{3}
}

func (x *VirtPayRequest) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

func (x *VirtPayRequest) GetPayMode() string {
	if x != nil {
		return x.PayMode
	}
	return ""
}

func (x *VirtPayRequest) GetSubType() string {
	if x != nil {
		return x.SubType
	}
	return ""
}

func (x *VirtPayRequest) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *VirtPayRequest) GetTraceno() string {
	if x != nil {
		return x.Traceno
	}
	return ""
}

func (x *VirtPayRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *VirtPayRequest) GetAccountno() string {
	if x != nil {
		return x.Accountno
	}
	return ""
}

func (x *VirtPayRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *VirtPayRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *VirtPayRequest) GetCertno() string {
	if x != nil {
		return x.Certno
	}
	return ""
}

func (x *VirtPayRequest) GetBankno() string {
	if x != nil {
		return x.Bankno
	}
	return ""
}

func (x *VirtPayRequest) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *VirtPayRequest) GetBankType() string {
	if x != nil {
		return x.BankType
	}
	return ""
}

func (x *VirtPayRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type VirtPayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespCode    string `protobuf:"bytes,1,opt,name=respCode,proto3" json:"respCode,omitempty"`
	Message     string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Traceno     string `protobuf:"bytes,3,opt,name=traceno,proto3" json:"traceno,omitempty"`
	Orderno     string `protobuf:"bytes,4,opt,name=orderno,proto3" json:"orderno,omitempty"`
	Amount      string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	TransStatus string `protobuf:"bytes,6,opt,name=transStatus,proto3" json:"transStatus,omitempty"`
	PayStatus   string `protobuf:"bytes,7,opt,name=payStatus,proto3" json:"payStatus,omitempty"`
	PayMsg      string `protobuf:"bytes,8,opt,name=payMsg,proto3" json:"payMsg,omitempty"`
	Signature   string `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *VirtPayResponse) Reset() {
	*x = VirtPayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_zhongbang_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtPayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtPayResponse) ProtoMessage() {}

func (x *VirtPayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zhongbang_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtPayResponse.ProtoReflect.Descriptor instead.
func (*VirtPayResponse) Descriptor() ([]byte, []int) {
	return file_proto_zhongbang_proto_rawDescGZIP(), []int{4}
}

func (x *VirtPayResponse) GetRespCode() string {
	if x != nil {
		return x.RespCode
	}
	return ""
}

func (x *VirtPayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VirtPayResponse) GetTraceno() string {
	if x != nil {
		return x.Traceno
	}
	return ""
}

func (x *VirtPayResponse) GetOrderno() string {
	if x != nil {
		return x.Orderno
	}
	return ""
}

func (x *VirtPayResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *VirtPayResponse) GetTransStatus() string {
	if x != nil {
		return x.TransStatus
	}
	return ""
}

func (x *VirtPayResponse) GetPayStatus() string {
	if x != nil {
		return x.PayStatus
	}
	return ""
}

func (x *VirtPayResponse) GetPayMsg() string {
	if x != nil {
		return x.PayMsg
	}
	return ""
}

func (x *VirtPayResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type VirtOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Traceno string `protobuf:"bytes,1,opt,name=traceno,proto3" json:"traceno,omitempty"`
}

func (x *VirtOrderRequest) Reset() {
	*x = VirtOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_zhongbang_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtOrderRequest) ProtoMessage() {}

func (x *VirtOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zhongbang_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtOrderRequest.ProtoReflect.Descriptor instead.
func (*VirtOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_zhongbang_proto_rawDescGZIP(), []int{5}
}

func (x *VirtOrderRequest) GetTraceno() string {
	if x != nil {
		return x.Traceno
	}
	return ""
}

type BalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cardno string `protobuf:"bytes,1,opt,name=cardno,proto3" json:"cardno,omitempty"`
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_zhongbang_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zhongbang_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_zhongbang_proto_rawDescGZIP(), []int{6}
}

func (x *BalanceRequest) GetCardno() string {
	if x != nil {
		return x.Cardno
	}
	return ""
}

type BalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespCode  string `protobuf:"bytes,1,opt,name=respCode,proto3" json:"respCode,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Amount    string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance   string `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Transit   string `protobuf:"bytes,5,opt,name=transit,proto3" json:"transit,omitempty"`
	Frozen    string `protobuf:"bytes,6,opt,name=frozen,proto3" json:"frozen,omitempty"`
	Signature string `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_zhongbang_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zhongbang_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_zhongbang_proto_rawDescGZIP(), []int{7}
}

func (x *BalanceResponse) GetRespCode() string {
	if x != nil {
		return x.RespCode
	}
	return ""
}

func (x *BalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BalanceResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *BalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *BalanceResponse) GetTransit() string {
	if x != nil {
		return x.Transit
	}
	return ""
}

func (x *BalanceResponse) GetFrozen() string {
	if x != nil {
		return x.Frozen
	}
	return ""
}

func (x *BalanceResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type VirtNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount      string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Cardno      string `protobuf:"bytes,2,opt,name=cardno,proto3" json:"cardno,omitempty"`
	Fee         string `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
	Merchno     string `protobuf:"bytes,4,opt,name=merchno,proto3" json:"merchno,omitempty"`
	Message     string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Orderno     string `protobuf:"bytes,6,opt,name=orderno,proto3" json:"orderno,omitempty"`
	TransStatus string `protobuf:"bytes,7,opt,name=transStatus,proto3" json:"transStatus,omitempty"`
	PayStatus   string `protobuf:"bytes,8,opt,name=payStatus,proto3" json:"payStatus,omitempty"`
	Traceno     string `protobuf:"bytes,9,opt,name=traceno,proto3" json:"traceno,omitempty"`
	TransDate   string `protobuf:"bytes,10,opt,name=transDate,proto3" json:"transDate,omitempty"`
	TransTime   string `protobuf:"bytes,11,opt,name=transTime,proto3" json:"transTime,omitempty"`
	Signature   string `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *VirtNotifyRequest) Reset() {
	*x = VirtNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_zhongbang_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtNotifyRequest) ProtoMessage() {}

func (x *VirtNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zhongbang_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtNotifyRequest.ProtoReflect.Descriptor instead.
func (*VirtNotifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_zhongbang_proto_rawDescGZIP(), []int{8}
}

func (x *VirtNotifyRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *VirtNotifyRequest) GetCardno() string {
	if x != nil {
		return x.Cardno
	}
	return ""
}

func (x *VirtNotifyRequest) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *VirtNotifyRequest) GetMerchno() string {
	if x != nil {
		return x.Merchno
	}
	return ""
}

func (x *VirtNotifyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VirtNotifyRequest) GetOrderno() string {
	if x != nil {
		return x.Orderno
	}
	return ""
}

func (x *VirtNotifyRequest) GetTransStatus() string {
	if x != nil {
		return x.TransStatus
	}
	return ""
}

func (x *VirtNotifyRequest) GetPayStatus() string {
	if x != nil {
		return x.PayStatus
	}
	return ""
}

func (x *VirtNotifyRequest) GetTraceno() string {
	if x != nil {
		return x.Traceno
	}
	return ""
}

func (x *VirtNotifyRequest) GetTransDate() string {
	if x != nil {
		return x.TransDate
	}
	return ""
}

func (x *VirtNotifyRequest) GetTransTime() string {
	if x != nil {
		return x.TransTime
	}
	return ""
}

func (x *VirtNotifyRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_proto_zhongbang_proto protoreflect.FileDescriptor

var file_proto_zhongbang_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x7a, 0x68, 0x6f, 0x6e, 0x67, 0x62, 0x61, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x7a,
	0x68, 0x6f, 0x6e, 0x67, 0x62, 0x61, 0x6e, 0x67, 0x22, 0xa9, 0x01, 0x0a, 0x0f, 0x4f, 0x70, 0x65,
	0x6e, 0x41, 0x63, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x74, 0x72, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x72, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x65, 0x72, 0x74,
	0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x65, 0x72, 0x74, 0x6e, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x64,
	0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x6e, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6b, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x62, 0x61, 0x6e, 0x6b, 0x6e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x6e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x65, 0x72, 0x74,
	0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x65, 0x72, 0x74, 0x6e, 0x6f,
	0x22, 0xf0, 0x01, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x63, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x73,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44,
	0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x65, 0x72, 0x74, 0x6e, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x65, 0x72, 0x74, 0x6e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x86, 0x03, 0x0a, 0x0e, 0x56, 0x69, 0x72, 0x74, 0x50, 0x61, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x62, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55,
	0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x6e, 0x6f, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x6e,
	0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x6e, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x65, 0x72, 0x74, 0x6e, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x65,
	0x72, 0x74, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6b, 0x6e, 0x6f, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x6e, 0x6b, 0x6e, 0x6f, 0x12, 0x1a, 0x0a, 0x08,
	0x62, 0x61, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x61, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x89, 0x02, 0x0a,
	0x0f, 0x56, 0x69, 0x72, 0x74, 0x50, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x6e,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x6e, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x56, 0x69, 0x72, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x72, 0x61, 0x63, 0x65, 0x6e, 0x6f, 0x22, 0x28, 0x0a, 0x0e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x64,
	0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x6e, 0x6f,
	0x22, 0xc9, 0x01, 0x0a, 0x0f, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x7a, 0x65, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xd7, 0x02, 0x0a,
	0x11, 0x56, 0x69, 0x72, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61,
	0x72, 0x64, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64,
	0x6e, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x66, 0x65, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x6e, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x6e, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x6e, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x6e, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x6e, 0x6f, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x6e, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x44, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_zhongbang_proto_rawDescOnce sync.Once
	file_proto_zhongbang_proto_rawDescData = file_proto_zhongbang_proto_rawDesc
)

func file_proto_zhongbang_proto_rawDescGZIP() []byte {
	file_proto_zhongbang_proto_rawDescOnce.Do(func() {
		file_proto_zhongbang_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_zhongbang_proto_rawDescData)
	})
	return file_proto_zhongbang_proto_rawDescData
}

var file_proto_zhongbang_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_zhongbang_proto_goTypes = []interface{}{
	(*OpenAcctRequest)(nil),   // 0: proto.zhongbang.OpenAcctRequest
	(*OpenQueryRequest)(nil),  // 1: proto.zhongbang.OpenQueryRequest
	(*OpenAcctResponse)(nil),  // 2: proto.zhongbang.OpenAcctResponse
	(*VirtPayRequest)(nil),    // 3: proto.zhongbang.VirtPayRequest
	(*VirtPayResponse)(nil),   // 4: proto.zhongbang.VirtPayResponse
	(*VirtOrderRequest)(nil),  // 5: proto.zhongbang.VirtOrderRequest
	(*BalanceRequest)(nil),    // 6: proto.zhongbang.BalanceRequest
	(*BalanceResponse)(nil),   // 7: proto.zhongbang.BalanceResponse
	(*VirtNotifyRequest)(nil), // 8: proto.zhongbang.VirtNotifyRequest
}
var file_proto_zhongbang_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_zhongbang_proto_init() }
func file_proto_zhongbang_proto_init() {
	if File_proto_zhongbang_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_zhongbang_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenAcctRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_zhongbang_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_zhongbang_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenAcctResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_zhongbang_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtPayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_zhongbang_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtPayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_zhongbang_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_zhongbang_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_zhongbang_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_zhongbang_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_zhongbang_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_zhongbang_proto_goTypes,
		DependencyIndexes: file_proto_zhongbang_proto_depIdxs,
		MessageInfos:      file_proto_zhongbang_proto_msgTypes,
	}.Build()
	File_proto_zhongbang_proto = out.File
	file_proto_zhongbang_proto_rawDesc = nil
	file_proto_zhongbang_proto_goTypes = nil
	file_proto_zhongbang_proto_depIdxs = nil
}
